### ISSUE TITLE
Setup documentation

### ISSUE THREAD

**Issue by robertjf** [jeppe-smith/umbraco-ajax-form#1]
Hi,
Could you please provide a sample HTML snippet or some instructions detailing the setup of the javascript files - do we need to include both index.js as well as Umbraco-ajax-form.js, for example?

**Comment by jeppe-smith** [comment]
I suggest installing with `npm i umbraco-ajax-form` and then you can just import/require the module. Only index.js is needed.

**Comment by robertjf** [comment]
Thanks for getting back to me so quickly; but that doesn't really answer my question - are there any dependencies?  Where do I apply the import statement?

**Comment by jeppe-smith** [comment]
There are no dependencies. You need gulp, webpack, or another bundler to import it, and you can import it in any .js file included on your page.

**Comment by robertjf** [comment]
thanks for clarifying 👍 - that help :)
